name: spid-cie-php

networks:
    spid-cie-php-network:
        driver: bridge

services:
    php:
        build:
            context: .
            dockerfile: docker/Dockerfile-php
        networks:
            - spid-cie-php-network
        restart: unless-stopped
        volumes:
            - .:/spid-cie-php
            - ./www:/var/www

    nginx:
        build:
            context: .
            dockerfile: docker/Dockerfile-nginx
        ports:
            - "443:443"
        networks:
            - spid-cie-php-network
        restart: unless-stopped
        volumes:
            - .:/spid-cie-php
            - ./www:/var/www
