FROM nginx:stable-alpine AS base

EXPOSE 443

RUN apk add openssl

RUN openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
      -keyout /etc/ssl/private/snakeoil.key -out /etc/ssl/certs/snakeoil.crt \
      -subj "/C=IT/ST=Italy/L=Rome/O=Example/OU=IT Department/CN=example.com"

RUN chmod 600 /etc/ssl/private/snakeoil.key

COPY docker/default.conf /etc/nginx/conf.d/default.conf

CMD ["nginx", "-g", "daemon off;"]