FROM php:8.1-fpm-alpine AS build

WORKDIR /spid-cie-php

RUN apk add php-session \
    php-tokenizer \
    php-xml \
    php-ctype \
    php-curl \
    php-dom \
    php-fileinfo \
    php-mbstring \
    php-openssl \
    php-session \
    php-tokenizer \
    php-xml \
    php-ctype \
    php-xmlwriter \
    php-simplexml \
    php-gmp \
    gmp-dev \
    php-bcmath \
    composer \
    git

RUN docker-php-ext-install bcmath \
    gmp

EXPOSE 9000

COPY docker/docker-fpm.ini /usr/local/etc/php/conf.d/docker-fpm.ini

CMD ["php-fpm", "--nodaemonize"]
